### ISSUE TITLE
where is the training code?

### ISSUE THREAD

**Issue by iFighting** [zihangJiang/TokenLabeling#1]
where is the training code?

**Comment by yuanli2333** [comment]
Hi, 
we will release training code in the future as stating [here](https://github.com/zihangJiang/TokenLabeling#training)

**Comment by zhaoguangxiang** [comment]
> the

Thank you for your t2t-vit and expect your training scripts for token labeling

**Comment by zhaoguangxiang** [comment]
When will the training code&scripts be available.

**Comment by zihangJiang** [comment]
We have released our training code and segmentation models.
