### ISSUE TITLE
The model parameters couldn't be downloaded.

### ISSUE THREAD

**Issue by LITTLEKKKK** [zihangJiang/TokenLabeling#13]
The model parameters couldn't be downloaded.

**Comment by zihangJiang** [comment]
Hi @LITTLEKKKK , thanks for your interest. May I know which link is not working?

**Comment by LITTLEKKKK** [comment]
Each of them (for example, lvvit_m-56M-224-84.0.pth.tar). "xxxx could not be saved, because the source file could not be read.)
Maybe it's my problem.

**Comment by zihangJiang** [comment]
Could you try with the [Google drive link](https://drive.google.com/file/d/1uPDBtkriLm7mEB-tx3nYpWncjD-R0ulC/view?usp=sharing)?

**Comment by LITTLEKKKK** [comment]
I found that the problem is my VPN. Thanks.
