### ISSUE TITLE
A Bag of Training Techniques for ViT

### ISSUE THREAD

**Issue by qdd1234** [zihangJiang/TokenLabeling#14]
Hi, thanks for your wonderful work. I have a question that whether training techniques mentioned in the LV-Vit can be used in other 
downstream task like object detection? In your paper, I see that many of this techniques are used in ImageNet. Thanks!

**Comment by zihangJiang** [comment]
Thanks for your interest. Our token labeling objective is designed for training better vision transformer based model for image classification. The pre-trained model can be fine-tuned on downstream tasks like segmentation and detection. Other tricks like convolutional patch embedding and residual factor can also be used for downstream tasks. 

However, currently most object detection models are based on CNN backbone, and some recent advanced models are trained using only data from COCO dataset without ImageNet pre-train (like [YOLO](https://github.com/ultralytics/yolov5)). If you are interested in applying vision transformer for detection, you may want to take a look at some recent work like [YOLOS](https://github.com/hustvl/YOLOS), where our tricks are also applicable.
