### ISSUE TITLE
Can Token labeling reach higher than annotator model?

### ISSUE THREAD

**Issue by ErenBalatkan** [zihangJiang/TokenLabeling#20]
Greetings,

Thank you for this incredible research.

I would like to know if it is possible to use Token Labeling to achieve scores higher than that of the annotator model, I believe this was the case with VOLO D5 model where it achieved higher score than NFNet, model used for annotation.

**Comment by zihangJiang** [comment]
Yes, you can also refer to Figure 4 (Right) in [our paper](https://arxiv.org/pdf/2104.10858.pdf) for more results. The performance of the model is related to its capacity as well as the accuracy of the annotator model.
