### ISSUE TITLE
Could you please provide the training log ？

### ISSUE THREAD

**Issue by YangYangGirl** [zihangJiang/TokenLabeling#21]

**Comment by zihangJiang** [comment]
You can refer here for the training log of LV-ViT-S https://github.com/zihangJiang/TokenLabeling/issues/17#issuecomment-917027674 .

**Comment by YangYangGirl** [comment]
Thanks for your reply. I try to merge your code into the timm, but I can't reproduce your accuracy. Did I miss something?

python train.py /data/images --opt adamw --weight-decay 0.05 --lr 1.6e-3 --warmup-lr 1e-6 --min-lr 1e-5 --decay-epochs 30 --warmup-epochs 5 --reprob 0.25 --model lvvit_s -b  64 --apex-amp --img-size 224 --drop-path 0.1 --token-label --token-label-data /data/label_top5_train_nfnet  --token-label-size 14 --model-ema --model-ema-decay 0.9992 -j 8

[summary.csv](https://github.com/zihangJiang/TokenLabeling/files/7317365/summary.csv)

[job-4350719-20211009164547.log](https://github.com/zihangJiang/TokenLabeling/files/7317366/job-4350719-20211009164547.log)

**Comment by zihangJiang** [comment]
Can you check if you have your random augmentation `--aa` correctly enabled?
