### ISSUE TITLE
关于TokenLabel的疑问

### ISSUE THREAD

**Issue by HiIcy** [zihangJiang/TokenLabeling#25]
作者好，
请问下如果我不传token_label,
看起来是用的默认dataset，
那就感觉像是普通训练呢，那是否token_label_path是必传，
还是代码里会处理普通数据？我没看到呢

**Comment by zihangJiang** [comment]
Yes, if you don't pass `token_label_path`, it will not load token-level label data and use the vanilla training strategy.

**Comment by HiIcy** [comment]
ok,thanks
